### ISSUE TITLE
Change Building -> Department

### ISSUE THREAD

**Issue by ddinh0411** [ddinh0411/opensource_schoolDB#5]
For clarity, change the Building member variable in the Faculty & Staff Classes to the Department these groups work in, as some departments are in Multiple Buildings. Please update in Driver on what is being asked for and what is printed out.

**Comment by Lnrivas** [comment]
I will work on this issue tonight. Clarifying question: I don't see a Professor class. What do you mean by Professor class?

**Comment by ddinh0411** [comment]
Sorry about that Faculty stands for Professors (Full, Assistant, & Associate) and Staff are all other employees who are not Professors. The Issue has been edited to correct this.
